apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tagger
  template:
    metadata:
      labels:
        app: tagger
    spec:
      containers:
      - name: tagger
        image: tagger-image
        imagePullPolicy: IfNotPresent # tells Kubernetes to use the local image instead of pulling it from a remote registry
        command: ["python", "run.py", "--port", "4000", "--serve", "dev", "--enable-api"]
        ports:
        - containerPort: 4000