apiVersion: apps/v1
kind: Deployment
metadata:
  name: tagger
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tagger
  template:
    metadata:
      labels:
        app: tagger
    spec:
      containers:
      - name: tagger
        image: maorh10/tagger:latest
        imagePullPolicy: IfNotPresent # use a local version of the image if it exists, rather than pulling from Docker Hub
        command: ["python", "run.py", "--port", "4000", "--serve", "dev", "--enable-api"]
        ports:
        - containerPort: 4000