apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.frontendBuild.pvc.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.frontendBuild.pvc.size }}
