apiVersion: apps/v1
kind: Deployment
metadata:
  name: dal
spec:
  replicas: {{ index .Values.dal.replicaCount .Values.global.mode }}
  selector:
    matchLabels:
      app: dal
  template:
    metadata:
      labels:
        app: dal
    spec:
      containers:
      - name: dal
        image: "{{ .Values.dal.image.repository }}:{{ .Values.dal.image.tag }}"
        imagePullPolicy: {{ .Values.dal.image.pullPolicy }}
        command: {{ index .Values.dal.command .Values.global.mode | toYaml | nindent 12 }}
        ports:
        - containerPort: {{ .Values.dal.containerPort }}
