apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: {{ index .Values.server.replicaCount .Values.global.mode }}
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      initContainers:
      - name: build-frontend
        image: "{{ .Values.frontendBuild.image.repository }}:{{ .Values.frontendBuild.image.tag }}"
        imagePullPolicy: {{ .Values.frontendBuild.image.pullPolicy }}
        args: {{ include "frontendBuild.args" . | nindent 10 }}
        volumeMounts:
        - name: angular-dist
          mountPath: /app/dist
      containers:
      - name: server
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        imagePullPolicy: {{ .Values.server.image.pullPolicy }}
        args: {{ tpl (index .Values.server.args .Values.global.mode | toYaml) . | nindent 12 }}
        ports:
        - containerPort: {{ .Values.server.containerPort }}
        volumeMounts:
        - name: angular-dist
          mountPath: /app/dist
      volumes:
      - name: angular-dist
        emptyDir: {}
