kind: Service
apiVersion: v1
metadata:
  name: tagger
spec:
  selector:
    app: tagger
  ports:
  - protocol: TCP
    port: {{ .Values.tagger.service.port }} # the port on which the Service is exposed
    targetPort: {{ .Values.tagger.containerPort }} # This is the port on the pods (the targets) where the actual application is running