openapi: 3.0.0
info:
  title: Tagging API
  version: 1.0.0
  description: API for tagging sentences
servers:
  - url: http://localhost:3000
paths:
  /tag:
    get:
      summary: Retrieve tagged sentence
      description: Use to request a sentence tagging
      parameters:
        - in: query
          name: mode
          schema:
            type: string
          required: true
          description: Mode of tagging
        - in: query
          name: sentence
          schema:
            type: string
          required: true
          description: Sentence to be tagged
      responses:
        '200':
          description: A successful response with the tagged sentence
        '500':
          description: Error from tagging service
        '503':
          description: DAL service unavailable
