global:
  mode: dev # default mode. can be set to prod
  enableIngress: false # when set to true, will expose the app via port 80. otherwise will be served locally via port 3000

tagger:
  replicaCount:
    dev: 1
    prod: 2
  containerPort: 4000
  image:
    repository: maorh10/tagger
    pullPolicy: IfNotPresent
    tag: latest
  service:
    type: ClusterIP
    port: 4000
  command:
    dev: ["python", "run.py", "--port", "4000", "--serve", "dev", "--enable-api"]
    prod: ["python", "run.py", "--port", "4000", "--serve", "prod"]

mongo:
  replicaCount: 1
  containerPort: 27017
  service:
    port: 27017
  image:
    repository: mongo
    tag: "7.0.2"
  persistence:
    size: 1Gi

dal:
  replicaCount:
    dev: 1
    prod: 1
  containerPort: 5000
  image:
    repository: maorh10/dal
    pullPolicy: IfNotPresent
    tag: latest
  service:
    port: 5000
  command:
    dev: ["python", "run.py", "--mongo-uri", "mongodb://mongo:27017/", "--port", "5000", "--serve", "dev", "--enable-api"]
    prod: ["python", "run.py", "--mongo-uri", "mongodb://mongo:27017/", "--port", "5000", "--serve", "prod"]

server:
  replicaCount:
    dev: 1
    prod: 1
  containerPort: 3000
  service:
    port: 3000
  image:
    repository: maorh10/server
    pullPolicy: IfNotPresent
    tag: latest
  args:
    dev: ["--taggerUri", "tagger:4000", "--dalUri", "dal:5000", "--port", "3000", "--serve-client", "--enable-api"]
    prod: ["--taggerUri", "tagger:4000", "--dalUri", "dal:5000", "--port", "3000", "--serve-client"]

frontendBuild:
  image:
    repository: maorh10/frontend
    pullPolicy: IfNotPresent
    tag: latest
  args:
    dev: [] # these are place-holders to be overridden in the template
    prod: []
  serverUri:
    base: "localhost"
    port:
      enableIngress: 80
      disableIngress: 3000
  pvc:
    name: angular-dist-pvc
    size: 1Gi