name: Dal CI

on:
  push:
    paths:
      - 'src/dal/**'
      - '!src/dal/README.md' # Exclude README
  workflow_dispatch: # This event allows manual triggering

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        cd src/dal
        pip install -r requirements.txt

    - name: Format code with black
      run: |
        cd src/dal
        black --line-length 110 ./**/*.py

    - name: Lint the code
      run: |
        cd src/dal
        pylint --disable=R,C ./src

    - name: Run tests
      run: |
        cd src/dal
        python -m pytest -vv ./tests/

  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd src/dal
        make install

    - name: Format code with black
      run: |
        cd src/dal
        make format

    - name: Lint the code
      run: |
        cd src/dal
        make lint

    - name: Run tests
      run: |
        cd src/dal
        make test

    - name: Install coverage library
      run: |
        cd src/dal
        pip install coverage

    - name: Test with coverage
      run: |
        cd src/dal/tests
        python -m coverage run -m unittest

    - name: Generate coverage report
      run: |
        cd src/dal/tests
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: src/dal/tests/coverage.xml
        fail_ci_if_error: true
        flags: dal
