name: Tagger CI

on:
  push:
    paths:
      - 'tagger/**'
  workflow_dispatch: # This event allows manual triggering

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        pip install -r ./tagger/requirements.txt

    - name: Format code with black
      run: |
        cd tagger
        black .

    - name: Lint the code
      run: |
        cd tagger
        pylint --disable=R,C app

    - name: Run tests
      run: |
        cd tagger
        python -m pytest -vv ./tests/

  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd tagger
		make install

    - name: Format code with black
      run: |
        cd tagger
        make format

    - name: Lint the code
      run: |
        cd tagger
        make lint

    - name: Run tests
      run: |
        cd tagger
        make test
