name: Tagger Coverage Report

on:
  push:
    paths:
      - 'src/tagger/**'
      - '!src/tagger/README.md' # Exclude README
  workflow_dispatch: # This event allows manual triggering

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd src/tagger
        make install
        pip install coverage

    - name: Test with coverage
      run: |
        cd src/tagger/tests
        python -m coverage run -m unittest

    - name: Generate coverage report
      run: |
        cd src/tagger/tests
        coverage report
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: src/tagger/tests/coverage.xml
        fail_ci_if_error: true
