name: Tagger CI

on:
  push:
    paths:
      - 'src/tagger/**'
      - '!src/tagger/README.md' # Exclude README
  workflow_dispatch: # This event allows manual triggering

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        cd src/tagger
        pip install -r requirements.txt

    - name: Format code with black
      run: |
        cd src/tagger
        black ./**/*.py

    - name: Lint the code
      run: |
        cd src/tagger
        pylint --disable=R,C ./src

    - name: Run tests
      run: |
        cd src/tagger/tests
        python -m pytest -vv .

  build-ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        cd src/tagger
        make install

    - name: Format code with black
      run: |
        cd src/tagger
        make format

    - name: Lint the code
      run: |
        cd src/tagger
        make lint

    - name: Run tests
      run: |
        cd src/tagger
        make test
