name: Tagger CI

on:
  push:
    paths:
      - 'tagger/**' # Trigger the workflow when there's a commit in the 'tagger' directory
  workflow_dispatch: # This event allows manual triggering

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: pip install -r tagger/requirements.txt

    - name: Run tests
      run: python -m pytest -vv tagger/tests/

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: pip install -r tagger/requirements.txt

    - name: Run tests
      run: python -m pytest -vv tagger/tests/

  finalize:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows] # Wait for both Linux and Windows jobs to complete

    steps:
    - name: Finalize
      run: echo "All tasks completed"
