name: Tagger CI

on:
  push:
    paths:
      - 'tagger/**'
  workflow_dispatch: # This event allows manual triggering

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        pip install -r ./tagger/requirements.txt
        pip install pytest

    - name: List files in the directory
      run: dir .

    - name: Run tests
      run: |
        cd tagger
        python -m pytest -vv ./tests/
